title: HydroSight
logo: https://github.com/peterson-tim-j/HydroSight/blob/master/GUI/icons/icon_webpage.png
show_downloads: true
description: Open-source data-driven hydrogeological insights
google_analytics: UA-72650036-1
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
